# Generated by Django 3.1.1 on 2020-10-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('posts', models.CharField(max_length=100)),
                ('subscribed_on_your_profile', models.CharField(max_length=50)),
                ('you_subscribed', models.CharField(max_length=50)),
                ('following', models.CharField(max_length=100)),
                ('followers', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('picture', models.URLField(max_length=255)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
    ]
